version: 3

tasks:

  run:
    cmds:
      - mix phx.server

  build:
    cmds:
      - mix compile

  shell:
    cmds:
      - iex -S mix
  fmt:
    cmds:
      - mix format

  lint:
    cmds:
      - mix credo --strict

  test:
    cmds:
      - mix test

  makemigration:
    cmds:
      - mix ecto.gen.migration {{.CLI_ARGS}}

  migrate:
    cmds:
      - mix ecto.migrate
