version: 3

tasks:

  run:
    cmds:
      - mix phx.server

  fmt:
    cmds:
      - mix format

  lint:
    cmds:
      - mix credo --strict

  makemigration:
    cmds:
      - mix ecto.gen.migration {{.CLI_ARGS}}

  migrate:
    cmds:
      - mix ecto.migrate
