version: 3

dotenv: ['.env']

tasks:

  run:
    cmds:
      - mix phx.server

  build:
    cmds:
      - mix compile --warnings-as-errors

  shell:
    cmds:
      - iex -S mix

  fmt:
    cmds:
      - mix format

  lint:
    cmds:
      - git ls-files | xargs ec
      - mix format --check-formatted
      - mix credo --strict

  test:
    cmds:
      - mix test

  makemigration:
    cmds:
      - mix ecto.gen.migration {{.CLI_ARGS}}

  migrate:
    cmds:
      - mix ecto.migrate
