version: 3

dotenv: ['.env']

tasks:

  run:
    cmds:
      - mix phx.server

  build:
    cmds:
      - mix compile --warnings-as-errors

  shell:
    cmds:
      - iex -S mix

  fmt:
    cmds:
      - mix format

  lint:
    cmds:
      - git ls-files | xargs ec
      - mix format --check-formatted
      - mix credo --strict

  test:
    cmds:
      - mix test

  makemigration:
    cmds:
      - mix ecto.gen.migration {{.CLI_ARGS}}

  migrate:
    cmds:
      - mix ecto.migrate

  deploy:
    desc: "Deploy the application to Docker Swarm (usage: task deploy --tag v0.1.0)"
    vars:
      tag:
        sh: 'echo ${tag:-}'
    cmds:
      - |
        if [ -z "{{.tag}}" ]; then
          echo "Error: tag is not provided! Example: task deploy --tag v0.1.0"
          exit 1
        fi
        TAG_NAME={{.tag}} envsubst < infra/docker-compose.prod.yml | docker stack deploy -c - croniq
