---
services:
  croniq:
    image: blablatdinov/croniq:${TAG_NAME}
    command: bin/croniq start
    restart: always
    ports:
      - 4010:4010
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DOMAIN: ${DOMAIN}
      PHX_SERVER: true
      PHX_HOST: ${PHX_HOST}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      PORT: 4010
      RECAPTCHA_SITE_KEY: ${RECAPTCHA_SITE_KEY}
      RECAPTCHA_SECRET_KEY: ${RECAPTCHA_SECRET_KEY}
      RECAPTCHA_SITE_KEY_V2: ${RECAPTCHA_SITE_KEY_V2}
      RECAPTCHA_SECRET_KEY_V2: ${RECAPTCHA_SECRET_KEY_V2}
      BREVO_API_KEY: ${BREVO_API_KEY}
      REGISTRATION_ENABLED: ${REGISTRATION_ENABLED}
